# Generated by Django 3.1.5 on 2021-07-09 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tape.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=tape.models.channel_directory_path)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('category', models.CharField(default='uncategorised', max_length=255)),
                ('videofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tape.videofiles')),
            ],
        ),
    ]
