# Generated by Django 3.1.5 on 2021-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='category',
            field=models.CharField(default='untagged', max_length=255),
        ),
    ]
