# Generated by Django 3.2.9 on 2021-12-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.CharField(choices=[('GU', 'Guest'), ('MR', 'Mentor'), ('ME', 'Mentee')], default='GU', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='This user has no bio', max_length=200),
        ),
    ]
